version: '3'
services:
  dhbw-t3100-frontend:
    build: ./frontend
    image: dhbw-t3100-frontend
    container_name: dhbw-t3100-frontend
    command: npm run start
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      development:

  dhbw-t3100-backend:
    build: ./backend
    image: dhbw-t3100-backend
    container_name: dhbw-t3100-backend
    command: npm run start
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      development:

  dhbw-t3100-postgres:
    image: "postgres:latest"
    container_name: dhbw-t3100-postgres
    env_file:
      - .env
    volumes:
    - database:/var/lib/postgres/data
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      development:

  dhbw-t3100-pgadmin:
    image: dpage/pgadmin4:4.25
    container_name: dhbw-t3100-pgadmin
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin4/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - "${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}"
    depends_on:
      - dhbw-t3100-postgres
    links:
      - dhbw-t3100-postgres
    networks:
      development:

  dhbw-t3100-mongo:
    image: mongo
    container_name: dhbw-t3100-mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes: 
      - mongo:/data/mongodb
      - ./db/init.js:/docker-entrypoint-initdb.d/init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INIT_DATABASE}
    networks:
      development:

  dhbw-t3100-mongo-express:
    image: mongo-express
    container_name: dhbw-t3100-mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: dhbw-t3100-mongo
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${MONGO_EXPRESS_ENABLE_ADMIN}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_ADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${MONGO_INIT_DATABASE}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - dhbw-t3100-mongo
    ports:
      - "8081:8081"
    networks:
      development:

volumes:
  database:
  mongo:
  pgadmin:

networks:
  development:
    driver: bridge